# Generated by Django 4.2.1 on 2024-08-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_category_name_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
