# Generated by Django 4.2.1 on 2024-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
